name: mention_tag_text_field
description: "A Flutter package which adds the mention or tag capabilities to existing TextField or TextFormField widget in Flutter."
version: 0.0.9
repository: "https://github.com/iWOLFSTEIN/mention_tag_text_field"

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
